NETSUITE_TABLES = [
    "ACCOUNTING_PERIODS",
    "ACCOUNTS",
    "CURRENCIES",
    "CUSTOMERS",
    "SUBSIDIARIES",
    "TRANSACTIONS",
    "TRANSACTION_LINES",
    "DEPARTMENTS",
    "INVOICES",
    "VENDORS",
    "ENTITY",
    "ITEMS"
]

PRIMARY_KEY_TABLES = {
    "ACCOUNTING_PERIODS": "ACCOUNTING_PERIOD_ID",
    "ACCOUNTS": "ACCOUNT_ID",
    "CURRENCIES": "CURRENCY_ID",
    "SUBSIDIARIES": "SUBSIDIARY_ID",
    "TRANSACTIONS": "TRANSACTION_ID",
    "TRANSACTION_LINES": "TRANSACTION_LINE_ID",
    "DEPARTMENTS": "DEPARTMENT_ID",
    "VENDORS": "VENDOR_ID",
    "ENTITY": "ENTITY_ID",
    "ITEMS": "ITEM_ID",
    "CUSTOMERS": "CUSTOMER_ID",
}

SF_DATATYPES = {
    "VARCHAR2": "VARCHAR",
    "NUMBER": "NUMBER",
    "STRING": "VARCHAR",
    "TIMESTAMP": "TIMESTAMP_NTZ(9)",
    "DATE": "TIMESTAMP_NTZ(9)",
    "INT": "NUMBER",
}

SOURCE_VIEW_KEYS = {
    "VW_STG_ACCOUNTING_PERIODS": "ACCOUNTING_PERIOD_ID",
    "VW_STG_ACCOUNTS": "ACCOUNT_ID",
    "VW_STG_CURRENCIES": "CURRENCY_ID",
    "VW_STG_COA": "DW_KEY_ID",
    "VW_STG_SUBSIDIARIES": "SUBSIDIARY_ID",
    "VW_STG_DEPARTMENTS": "DEPARTMENT_ID",
    "VW_STG_VENDORS": "VENDOR_ID",
    "VW_STG_ENTITY": "ENTITY_ID",
    "VW_STG_ITEMS": "ITEM_ID",
    "VW_STG_CUSTOMERS": "CUSTOMER_ID",
}


def getNetsuiteTables():
    return NETSUITE_TABLES


def getPrimaryKeyTables():
    return PRIMARY_KEY_TABLES


def getDataTypes():
    return SF_DATATYPES


def getSourceViewKeys():
    return SOURCE_VIEW_KEYS
